version: 0.0
Resources:
  - TargetService:
      Type: AWS:ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:548593215839:task-definition/poc-548593215839-FargateECSCluster-TaskDefinition-fMuGdqto6pi9:2"
        LoadBalancerInfo:
          ContainerName: "poc-Container"
          ContainerPort: 80
